### ISSUE TITLE
Are you going to release the code?

### ISSUE THREAD

**Issue by chenxshuo** [amazon-science/llm-interpret#1]
Hi all, 

thank you very much for this awesome project! 
I wonder whether you are going to release the code in the near future.

Thank you.

**Comment by g-karthik** [comment]
Hi @chenxshuo apologies for the delay, yes I am currently working on packaging the code in an easy-to-use fashion, will let you know when it is pushed. Thanks!

**Comment by g-karthik** [comment]
@chenxshuo I have released the code with a detailed README, I hope you find it useful! Thanks!
